import os
import sys
from data_saver import DataSaver
from database import ScienceRecommender, create_engine


def main():
    """Главная функция для запуска всей системы."""

    # Инициализация
    saver = DataSaver()

    print("=== Scientific Articles Parser and Recommender ===")
    print("1. Parse and save articles")
    print("2. Get recommendations")
    print("3. Run demo")

    choice = input("\nChoose option (1-3): ").strip()

    lst = ["Алексей Хохлов",
    "Михаил Гельфанд",
    "Александр Кабанов",
    "Сергей Недоспасов",
    "Артём Оганов",
    "Михаил Фейгельман",
    "Владимир Захаров",
    "Андрей Зализняк",
    "Виктор Васильев",
    "Александр Кулешов",
    "Евгений Кунин",
    "Константин Северинов",
    "Михаил Спирин",
    "Сергей Лукьянов",
    "Александр Габибов",
    "Владимир Скулачёв",
    "Михаил Кирпичников",
    "Алексей Семёнов",
    "Юрий Оганесян",
    "Валерий Рубаков",
    "Александр Литвак",
    "Игорь Меглинский",
    "Сергей Дмитриев",
    "Андрей Трофимук",
    "Павел Певзнер",
    "Михаил Ройтберг",
    "Александр Шалимов",
    "Владимир Болдырев",
    "Сергей Алдошин",
    "Александр Кислов",
    "Дмитрий Тонконогов",
    "Ирина Донецкая",
    "Елена Григоренко",
    "Андрей Десницкий",
    "Сергей Попов",
    "Михаил Гельфанд",
    "Александр Марков",
    "Светлана Боринская",
    "Владимир Шувалов",
    "Алексей Старобинский",
    "Рустам Сайфулин",
    "Андрей Линде",
    "Виктория Попова",
    "Сергей Петухов",
    "Михаил Кацнельсон",
    "Александр Белавин",
    "Владимир Захаров-Мэнский",
    "Игорь Волобуев",
    "Сергей Гаврилов",
    "Андрей Варламов",
    "Михаил Данилов",
    "Александр Долгов",
    "Сергей Рубин",
    "Владимир Лукаш",
    "Алексей Фридман",
    "Михаил Сажин",
    "Сергей Сазонов",
    "Андрей Сергеев",
    "Дмитрий Горбунов",
    "Михаил Иванцов",
    "Александр Панов",
    "Сергей Блинников",
    "Владимир Липунов",
    "Алексей Моисеев",
    "Михаил Прохоров",
    "Сергей Фабричный",
    "Андрей Бычков",
    "Дмитрий Вибе",
    "Михаил Ревнивцев",
    "Александр Лутовинов",
    "Сергей Гребенев",
    "Владимир Назаров",
    "Алексей Вихлянцев",
    "Михаил Павлинский",
    "Сергей Сазонов",
    "Андрей Лобанов",
    "Дмитрий Семёнов",
    "Михаил Роттер",
    "Александр Степанов",
    "Сергей Богачёв",
    "Владимир Красносельских",
    "Алексей Струминский",
    "Михаил Зеленый",
    "Сергей Пулинец",
    "Андрей Дементьев",
    "Дмитрий Климушкин",
    "Михаил Панасюк",
    "Александр Лукьянов",
    "Сергей Шайдуров",
    "Владимир Калегаев",
    "Алексей Ким",
    "Михаил Кайгородов",
    "Сергей Тихоцкий",
    "Андрей Медведев",
    "Дмитрий Глушков",
    "Михаил Нефёдов",
    "Александр Родин",
    "Сергей Никитский",
    "Владимир Краснопольский",
    "Алексей Малахов"]
    lst = [
    # --- Топ / Академики / Известные ---
    "Артём Оганов", "Рашид Сюняев", "Юрий Оганесян", "Алексей Старобинский", "Александр Сергеев",
    "Геннадий Месяц", "Александр Литвак", "Лев Зеленый", "Владимир Захаров", "Александр Холево",
    "Виктор Садовничий", "Валерий Козлов", "Дмитрий Трещев", "Альберт Ширяев", "Борис Кашин",
    "Сергей Кисляков", "Юрий Матиясевич", "Александр Буфетов", "Сергей Ландо", "Иван Ященко",
    "Алексей Семенов", "Виктор Васильев", "Александр Разборов", "Александр Кулешов", "Иван Оселедец",
    "Дмитрий Ветров", "Константин Воронцов", "Андрей Райгородский", "Александр Гасников", "Вадим Стрижов",
    "Евгений Бурнаев", "Виктор Лемпицкий", "Алексей Досовицкий", "Сергей Николенко", "Александр Дьяконов",
    "Михаил Гельфанд", "Константин Северинов", "Всеволод Макеев", "Алексей Хохлов", "Григорий Трубников",

    # --- Физика (Теория, Ядерная, Плазма, Астро) ---
    "Эдуард Боос", "Михаил Данилов", "Виктор Матвеев", "Павел Пахлов", "Александр Белавин",
    "Михаил Высоцкий", "Дмитрий Казаков", "Борис Шарков", "Игорь Ткачев", "Валерий Рубаков",
    "Алексей Васильев", "Андрей Славнов", "Борис Иоффе", "Леонид Келдыш", "Спартак Беляев",
    "Владимир Кадышевский", "Семен Герштейн", "Лев Окунь", "Геннадий Бисноватый-Коган", "Александр Долгов",
    "Игорь Новиков", "Николай Шакура", "Дмитрий Варшалович", "Юрий Парийский", "Анатолий Черепащук",
    "Владимир Сурдин", "Сергей Попов", "Борис Штерн", "Михаил Ревнивцев", "Евгений Чуразов",
    "Марат Гильфанов", "Алексей Вихлинин", "Сергей Сазонов", "Владимир Драчев", "Андрей Федянин",
    "Владимир Белотелов", "Юрий Кившарь", "Михаил Лиманский", "Сергей Апресян", "Александр Горский",
    "Андрей Зотов", "Антон Миронов", "Алексей Морозов", "Андрей Миронов", "Никита Некрасов",
    "Самсон Шаташвили", "Федор Смирнов", "Владимир Казаков", "Иван Костин", "Валерий Рязанов",
    "Олег Астафьев", "Алексей Устинов", "Валерий Винокур", "Михаил Фейгельман", "Лев Иоффе",
    "Александр Финкельштейн", "Дмитрий Поляков", "Игорь Клебанов", "Андрей Линде", "Александр Поляков",

    # --- Математика и Механика ---
    "Сергей Новиков", "Яков Синай", "Григорий Маргулис", "Владимир Дринфельд", "Ефим Зельманов",
    "Максим Концевич", "Владимир Воеводский", "Григорий Перельман", "Станислав Смирнов", "Андрей Окуньков",
    "Дмитрий Орлов", "Александр Кузнецов", "Сергей Гуков", "Антон Зорич", "Борис Фейгин",
    "Михаил Финкельберг", "Александр Бейлинсон", "Виктор Гинзбург", "Владимир Барановский", "Роман Безрукавников",
    "Михаил Капранов", "Николай Решетихин", "Владимир Тураев", "Олег Виро", "Юрий Бураго",
    "Анатолий Вершик", "Сергей Дузов", "Николай Макаров", "Станислав Смирнов", "Дмитрий Челкак",
    "Евгения Малинникова", "Александр Логунов", "Федор Назаров", "Леонид Полтерович", "Михаил Громов",
    "Юрий Манин", "Борис Дубровин", "Игорь Кричевер", "Сергей Натанзон", "Армен Сергеев",
    "Александр Шень", "Николай Верещагин", "Эдуард Гирш", "Дмитрий Ицыксон", "Александр Охотин",
    "Юрий Нестеров", "Аркадий Немировский", "Борис Поляк", "Александр Назин", "Владимир Протасов",

    # --- Computer Science / ML / AI / Data Science ---
    "Руслан Салахутдинов", "Алексей Эфрос", "Сергей Левин", "Илья Суцкевер", "Андрей Карпаты",
    "Ярослав Ганин", "Дмитрий Ульянов", "Александр Шапел", "Антон Осокин", "Екатерина Лобачева",
    "Надежда Чиркова", "Дмитрий Кропотов", "Артем Бабенко", "Глеб Гусев", "Павел Сердюков",
    "Людмила Остерман", "Андрей Устюжанин", "Денис Деркач", "Федор Ратников", "Михаил Хусид",
    "Александр Панов", "Алексей Ковалев", "Илья Макаров", "Михаил Беляев", "Борис Гутман",
    "Максим Шараев", "Олег Иванов", "Евгений Соколов", "Павел Рыбников", "Никита Казеев",
    "Алексей Артёмов", "Евгений Зайцев", "Дмитрий Соломенцев", "Александр Коротин", "Никита Балландов",
    "Сергей Бартунов", "Кирилл Струминский", "Даниил Поляков", "Александр Новиков", "Антон Родионова",

    # --- Химия / Материаловедение / Биофизика ---
"Валерий Фокин", "Владимир Геврасев", "Валентин Анаников", "Ирина Белецкая", "Юрий Золотов",
    "Аслан Цивадзе", "Сергей Алдошин", "Михаил Алфимов", "Сергей Варфоломеев", "Степан Калмыков",
    "Олег Синяшин", "Владимир Минкин", "Борис Трофимов", "Чарыяр Ярмухамедов", "Вячеслав Власов",
    "Ольга Донцова", "Александр Габибов", "Сергей Деев", "Михаил Кирпичников", "Владимир Скулачев",
    "Сергей Недоспасов", "Евгений Свердлов", "Сергей Лукьянов", "Всеволод Ткачук", "Рауль Гайнетдинов",
    "Алексей Томилин", "Сергей Колесников", "Андрей Лисицын", "Владимир Чехонин", "Александр Макаров",

    # --- Региональные / СНГ (Казахстан, Беларусь, Украина и др.) ---
    "Ратбай Мырзакулов", "Эрнст Боос", "Мухтарбай Отелбаев", "Тынысбек Кальменов", "Нарул Уалиев",
    "Галымкаир Мутанов", "Бакытжан Жумагулов", "Аскар Джумадильдаев", "Уалбай Умирбаев", "Максат Калимолдаев",
    "Сергей Абламейко", "Владимир Агабеков", "Николай Казак", "Олег Ивашкевич", "Сергей Килин",
    "Александр Тузиков", "Михаил Артемьев", "Валентин Орлович", "Сергей Гапоненко", "Петр Витязь",
    "Борис Патон", "Антон Наумовец", "Вадим Локтев", "Анатолий Загородний", "Владимир Горбулин",
    "Ярослав Яцкив", "Александр Копыленко", "Сергей Комиссаренко", "Анна Ельская", "Владимир Семиноженко",
    "Валерий Кухар", "Вячеслав Петров", "Владимир Моргун", "Николай Картель", "Александр Кириленко",

    # --- Дополнительно (Активные исследователи ВШЭ, Сколтех, МФТИ, ИТМО) ---
    "Павел Белов", "Дмитрий Зуев", "Сергей Макаров", "Валентин Миличко", "Михаил Петров",
    "Андрей Богданов", "Иван Иорш", "Александр Подымов", "Алексей Словеснов", "Ксения Барышникова",
    "Полина Капитанова", "Станислав Глыбовский", "Алексей Шнаптицев", "Георгий Зограф", "Михаил Зюзин",
    "Владимир Виноградов", "Александр Виноградов", "Евгений Пидолько", "Максим Винник", "Дарья Смирнова",
    "Андрей Рогачев", "Дмитрий Федосов", "Александр Корсунский", "Игорь Алабужев", "Алексей Ремизович",
    "Владимир Велихов", "Михаил Ковальчук", "Евгений Велихов", "Роберт Нигматулин", "Александр Асеев",
    "Валентин Пармон", "Ренад Сагдеев", "Дмитрий Маркович", "Сергей Алексеенко", "Николай Похиленко",
    "Михаил Эпов", "Анатолий Деревянко", "Вячеслав Молодин", "Валерий Тишков", "Анатолий Пантелеев",
    "Юрий Шокин", "Александр Латышев", "Сергей Псахье", "Николай Колчанов", "Валентин Власов",
    "Иосиф Гительзон", "Евгений Ваганов", "Александр Шкуратов", "Юрий Балега", "Геннадий Матишов",
    "Дмитрий Матишов", "Александр Чибисов", "Владимир Иванов", "Борис Четверушкин", "Ирина Горячева",
    "Владимир Климов", "Леопольд Леонтьев", "Николай Макаров", "Александр Чубарьян", "Валерий Чарушин",
    "Олег Чупахин", "Валерий Черешнев", "Виктор Руденко", "Владимир Большаков", "Александр Татаркин",
    "Виктор Полтерович", "Руслан Гринберг", "Александр Некипелов", "Сергей Глазьев", "Владимир Квинт",
    "Абел Аганбегян", "Борис Порфирьев", "Виктор Ивантер", "Владимир Маевский", "Георгий Клейнер"
]
    names = [
        "A. A. Varlamov",
        "A. Barone",
        "A. Bilmes",
        "A. Blanchet",
        "A. Bonnemaison",
        "A. Castellón",
        "A. E. Karneyeu",
        "A. E. Nikiforov",
        "A. Fabich",
        "A. Forchel",
        "A. G. Demin",
        "A. Gardikiotis",
        "A. I. Ivanov",
        "A. I. Panov",
        "A. I. Rodionov",
        "A. L. Pankratov",
        "A. M. Artikov",
        "A. M. Sergeev",
        "A. M. Tokman",
        "A. R. Matanin",
        "A. S. Brichkin",
        "A. S. Chepurnov",
        "A. S. Grebenev",
        "A. S. Pozanenko",
        "A. Spörl",
        "A. V. Boikov",
        "A. V. Chiginev",
        "A. V. Derbin",
        "A. V. Dermenev",
        "A. V. Kachanov",
        "A. V. Prosvetov",
        "A. V. Ridnaya",
        "A. V. Sekretenko",
        "A. V. Yudin",
        "A. Ya. Rodionov",
        "A. Yu. Morozov",
        "A. Yu. Orlov",
        "A. Yu. Zaharov",
        "A. A. Abrikosov, Jr.",
        "Aaron C. Trigg",
        "Aaron Couture",
        "Aaron Szasz",
        "Abraham Asfaw",
        "Adam Khoja",
        "Adamantia Paizis",
        "Aditya Narendra",
        "Adrian Vetter",
        "Agustin Di Paolo",
        "Ahmed Omran",
        "Aimee L. Hungerford",
        "Albert Domingo",
        "Albert Frisch",
        "Alberto J. Castro-Tirado",
        "Albertos Domingo",
        "Aleksei A. Kabanov",
        "Aleksei Dmitriev",
        "Aleksei Staroverov",
        "Aleksei Ustimenko",
        "Aleksandr Artemev",
        "Aleksandr Beznosikov",
        "Aleksandr I. Panov",
        "Aleksandr N. Grekov",
        "Aleksandr Ometov",
        "Aleksandr Panov",
        "Aleksandr Petiushko",
        "Aleksandr Zinovev",
        "Aleksandra V. Mishakina",
        "Alexander Barone",
        "Alexander Bilmes",
        "Alexander Bondar",
        "Alexander Gasnikov",
        "Alexander Heger",
        "Alexander Martynov",
        "Alexander Rogozin",
        "Alexander Schuckert",
        "Alexander S. Chepurnov",
        "Alexei A. Korytin",
        "Alexei I. Korytin",
        "Alexei V. Kavokin",
        "Alexey Belyanin",
        "Alexey D. Nekrasov",
        "Alexey K. Kovalev",
        "Alexey Naumov",
        "Alexey Skrynnik",
        "Alexis Coleiro",
        "Alexis Morvan",
        "Alice Gatti",
        "Almudena Arcones",
        "Amit Devra",
        "Amit K. Ror",
        "An V. Barone",
        "Anastasiya Runnova",
        "Anatoly Ya. Rodionov",
        "Andraej Sporl",
        "Andre Petukhov",
        "Andrej Babic",
        "Andrei A. Varlamov",
        "Andrei Gorodetsky",
        "Andrei Linde",
        "Andrei P. Igoshev",
        "Andrei Sergeev",
        "Andrei Slepnev",
        "Andrei Spiridonov",
        "Andrei Vasenin",
        "Andrej Babic",
        "Andreas Bengtsson",
        "Andreas Elben",
        "Andreas Spörl",
        "Andrey Bykov",
        "Andrey Gorodetsky",
        "Andrey L. Pankratov",
        "Angel Abusleme",
        "Angela Bazzano",
        "Aniket Rath",
        "Anish Agrawal",
        "Anna Lekontseva",
        "Anna V. Ridnaia",
        "Anjasha Gangopadhyay",
        "Anthony J. Bird",
        "Anton Andreychuk",
        "Anton Proskurnikov",
        "Antonella Molinaro",
        "Antonio Bergnoli",
        "Antony J. Bird",
        "Arash Bodaghee",
        "Arnav Chopra",
        "Artem Pshenitsyn",
        "Asaf Aharoni",
        "Ashna Gulati",
        "Ashok Ajoy",
        "Ben Chiaro",
        "Benoit Vermersch",
        "Bernhard Mueller",
        "Bernhard Müller",
        "Bhagya M. Subrayan",
        "Bob B. Buckley",
        "Bo Li",
        "Bradley Cenko",
        "Brajesh Kumar",
        "Brian Ballard",
        "Brian Burkett",
        "Brijesh Kumar",
        "Bryce Kobrin",
        "Burin Asavapibhop",
        "C. Alt",
        "C. Schneider",
        "Carlo Ferrigno",
        "Catherine Erickson",
        "Cédric Cerna",
        "Charles Neill",
        "Chen Bo Calvin Zhang",
        "Chris L. Fryer",
        "Christian Bengs",
        "Claudia Campolo",
        "Claudia Dietze",
        "Colin Gaffney",
        "Costas Andreopoulos",
        "Cyrus Rashtchian",
        "D. Banerjee",
        "D. Barrow",
        "D. Cooke",
        "D. K. Sahu",
        "D. V. Kirpichnikov",
        "D. V. Livanov",
        "Da-Ming Wei",
        "Daichi Hiramatsu",
        "Dan Milisavljevic",
        "Dan Zhang",
        "Daniel Bick",
        "Daniela Bortoletto",
        "Daniil Zelezetsky",
        "Dara Bahri",
        "Daren Anderson",
        "Dario Rossi",
        "Dave Bacon",
        "David A. Browne",
        "David A. Buell",
        "David A. H. Buckley",
        "David Adey",
        "David Arnett",
        "David Buckley",
        "Davide Basilico",
        "Debora Misenkova",
        "Didier Auguste",
        "Diederik Roest",
        "Dmitriy Kostunin",
        "Dmitry A. Abanin",
        "Dmitry Abanin",
        "Dmitry Dodonov",
        "Dmitry D. Frederiks",
        "Dmitry Makarov",
        "Dmitry Metelev",
        "Dmitry S. Gorbunov",
        "Dmitry S. Svinkin",
        "Dmitry V. Salnikov",
        "Dmitry Yudin",
        "Dmitrii A. Semenov",
        "Domenico Colella",
        "E. A. Dzhivelikian",
        "E. Churazov",
        "E. Depero",
        "E. I. Malevannaya",
        "E. I. Sorokina",
        "E. S. Moiseev",
        "E. V. Zikiy",
        "Eamonn Kennedy",
        "Ebrahim Forati",
        "Eduard E. Boos",
        "Egor Cherepanov",
        "Eleonora D'uva",
        "Elena A. Kronberg",
        "Elena Brylyakova",
        "Elena E. Grigorenko",
        "Elena I. Sorokina",
        "Elena Simona Lohan",
        "Elisa G. M. Ferreira",
        "Elisa Jones",
        "Elizaveta Rutskova",
        "Eliott Rosenberg",
        "Elliott Coe",
        "Enrico Bozzo",
        "Ercüment Kaya",
        "Eric Baussan",
        "Eric Bieber",
        "Eric Burns",
        "Eric Chu",
        "Eric Mansfield",
        "Eric Moulines",
        "Erik Kuulkers",
        "Evan McDonough",
        "Evan Rosen",
        "Evgenii V. Unzhakov",
        "Evgeny Gorbovskoy",
        "Evgenia Sitnikova",
        "F. Cadoux",
        "F. Dubinin",
        "Felix Fürst",
        "Felix Rohde",
        "Fengpeng An",
        "Floriane Cangemi",
        "Francesca Carnesecchi",
        "Francesco Barile",
        "Frank Arute",
        "Frank Timmes",
        "Franco Benotto",
        "Fred Adams",
        "G. Barr",
        "G. C. Anupama",
        "G. Yu. Mozgunov",
        "Gaurav Gyawali",
        "Gaurav Mishra",
        "Gayane Tyul'basheva",
        "Georg Aigeldinger",
        "Gheorghe Comanici",
        "Gianluca Aglieri Rinella",
        "Giacomo Alocco",
        "Giacomo Contin",
        "Gina Bortoli",
        "Gleb Fedorov",
        "Gregory Timp",
        "Grigory L. Litvinov",
        "Guangpeng An",
        "Guillaume Belanger",
        "H. Alarakia-Charles",
        "Hao Zhou",
        "Harim Jin",
        "Heikki Haario",
        "Hendrik Weichel",
        "Henrik Jacobsson",
        "Hossam Ahmed",
        "Hugh Zhang",
        "I. Alekseev",
        "I. A. Mereminskiy",
        "I. A. Rodionov",
        "I. V. Chelovekov",
        "I. V. Polozov",
        "Ian Benson",
        "Iannis Dandouras",
        "Ice Pasupat",
        "Idan Szpektor",
        "Ignacio Negueruela",
        "Igor A. Luk'yanchuk",
        "Igor Aleiner",
        "Igor Andreoni",
        "Igor I. Tkachev",
        "Ilia S. Drachnev",
        "Ilya Drozdov",
        "Ilya Mandel",
        "Inderjit Dhillon",
        "Isabel Caballero",
        "Ivan Oladyshkin",
        "J. P. Ostriker",
        "Jaeho Lee",
        "James K. Leung",
        "Janne Mäntylä",
        "Jari Nurmi",
        "Jason Hausenloy",
        "Jenna Bovaird",
        "Jerome Chenevez",
        "Jesse C. Hoke",
        "Jesse Hoke",
        "Jiawei Zhang",
        "Jilei Xu",
        "Jin-Ming Bai",
        "Joao Basso",
        "João Pedro Athayde Marcondes de André",
        "Johannes Bausch",
        "Johannes Motruk",
        "John Joseph Carrasco",
        "John Ling",
        "Jonathan A. Gross",
        "Jorge Echavarria",
        "Jose Joaquin Rodes-Roca",
        "Joseph C. Bardin",
        "Joseph Bardin",
        "Josephina Hu",
        "Juan Atalaya",
        "Julia Alfonso-Garzon",
        "Julia Alfonso-Garzón",
        "Julia Berndtsson",
        "Jürgen Kurths",
        "K. Adamowicz",
        "K. D. Ostashenko",
        "K. I. Gerasimov",
        "K. Sablon",
        "Kai Adamowicz",
        "Kastytis Zubovas",
        "Katie Auchettl",
        "Kenneth Ruud",
        "Kirill Muravyev",
        "Kirill Smirnov",
        "Kirill Zhirkov",
        "Konstantin Postnov",
        "Konstantin Severinov",
        "Konstantin Tikhonov",
        "Konstantin Yakovlev",
        "Kostyantyn Kechedzhi",
        "Krishna Haridasan",
        "Kunal Arya",
        "Kuntal Misra",
        "Kyle Anderson",
        "L. A. Falkovsky",
        "L. Bartoszek",
        "L. Bernardi",
        "L. Berns",
        "L. Ciotti",
        "L. V. Kravchuk",
        "Laleh Aghababaie Beni",
        "Laleh Aghababaie-Beni",
        "Lara Sidoli",
        "Laura B. Schulz",
        "Lennart Balkenhol",
        "Leon Brill",
        "Leonid V. Kravchuk",
        "Léo Van Damme",
        "Lev B. Ioffe",
        "Lev V. Dudko",
        "Lloyd Knox",
        "Long Phan",
        "Lorenzo Ducci",
        "Luca Aglietta",
        "Luca Carlone",
        "Lukas Bieger",
        "Lukas Burgholzer",
        "Lukas Konecny",
        "Lukas Schmid",
        "Luke Marris",
        "Lynn Kistler",
        "M. Ansmann",
        "M. H. Bui",
        "M. Kamp",
        "M. M. Kirsanov",
        "M. Revnivtsev",
        "M. Sh. Potashov",
        "M. Y. Reizer",
        "M. Yu. Ougrumov",
        "Malcolm J. Coe",
        "Mantas Mazeika",
        "Marcel Blistein",
        "Marcel Büchner",
        "Marco Beretta",
        "Margherita Buizza Avanzini",
        "Maria D. Caballero-García",
        "Marielle Chartier",
        "Marina Afonina",
        "Marina Sheshukova",
        "Marina Ushakova",
        "Marius Baab",
        "Marius Kadek",
        "Mark Drapes",
        "Markus Ansmann",
        "Markus Fränz",
        "Martin Kaupp",
        "Martin Knudsen",
        "Martin R. Oswald",
        "Martin Simon",
        "Martin Schulz",
        "Martino Michelotti",
        "Martín Letras",
        "Marat Sh. Potashov",
        "Masato Sato",
        "Matias Antonelli",
        "Matthew Daniel Buckland",
        "Matthew G. Baring",
        "Matthew Neeley",
        "Matteo Ippoliti",
        "Matthias Bissinger né Kühnel",
        "Matthias Ehle",
        "Maurizio Falanga",
        "Max Werninghaus",
        "Maxim A. Gorlach",
        "Maxim V. Libanov",
        "Maxim V. Trushin",
        "Maxim Zhuravlev",
        "Michael Broughton",
        "Michael Choi",
        "Michael Doroshenko",
        "Michael Ermoshin",
        "Michael M. Merkin",
        "Michael Reizer",
        "Michael S. Briggs",
        "Miao He",
        "Michal Repisky",
        "Michela Negro",
        "Mike Schaekermann",
        "Mohamed Shaaban",
        "Motoko Serino",
        "Mridweeka Singh",
        "Muhammad Nufail Farooqi",
        "N. A. Gippius",
        "N. Babu",
        "N. K. Chakradhari",
        "N. S. Smirnov",
        "N. V. Dunina-Barkovskaya",
        "N. V. Krasnikov",
        "Nadezhda Semenova",
        "Nan-Jiang Jiang",
        "Nathan Lintz",
        "Nathaniel Li",
        "Naseem Bouchhar",
        "Nebil Cinar",
        "Nelson L. Christensen",
        "Niccolo Di Lalla",
        "Nicholas Bushnell",
        "Nicola Omodei",
        "Nikita Astrakhantsev",
        "Nikita Balashov",
        "Nikita Bessonov",
        "Nikita Kachaev",
        "Nikita Oskolkov",
        "Nikolas Pomplun",
        "Nikolay Anfimov",
        "Nikunj Saunshi",
        "Noora Färkkilä",
        "Noveen Sachdeva",
        "Nozomu Tominaga",
        "Oleg Astafiev",
        "Olga L. Malkina",
        "Oliver J. Roberts",
        "Oliver Zhang",
        "Omar Abdelrahman",
        "Ori Ram",
        "P. Becht",
        "P. Camerini",
        "P. Crivelli",
        "P. Yu. Minaev",
        "Pablo Reig",
        "Pascal Becht",
        "Patrick W. Daly",
        "Paul Klimov",
        "Pavel A. Belov",
        "Pavel A. Pevzner",
        "Pavel Balanutsa",
        "Pavel Pevzner",
        "Pere Blay",
        "Peter Kretschmar",
        "Peter Veres",
        "Petr S. Satunin",
        "Polina Fedotova",
        "R. A. Sunyaev",
        "R. Krivonos",
        "R. R. Dusaev",
        "Rahul Gupta",
        "Rakhim Davletkaliyev",
        "Rasmus Vikhamar-Sandberg",
        "Rashid Sunyaev",
        "Raya Dastidar",
        "Renata Kallosh",
        "Renyi Chen",
        "Rhine Samajdar",
        "Richard Allen",
        "Richard Ren",
        "Robert Wille",
        "Roberto Baccomi",
        "Roberto Barbera",
        "Roberto Turolla",
        "Rodrigo Gonzalez Quaglia",
        "Roland Diehl",
        "Roman Gavrilenko",
        "Ross Alcaraz",
        "Ryan Babbush",
        "Ryan Kim",
        "S. Abe",
        "S. Arimoto",
        "S. Bhattacharjee",
        "S. Bordoni",
        "S. G. Kovalenko",
        "S. G. Tikhodeev",
        "S. Höfling",
        "S. I. Blinnikov",
        "S. I. Novikov",
        "S. Iyyani",
        "S. M. Natanzon",
        "S. N. Gninenko",
        "S. S. Gavrilov",
        "S. Shilling",
        "S. V. Donskov",
        "S. V. Kotomanov",
        "S. Yu. Alekseev",
        "S. Yu. Sazonov",
        "Sabrina Hong",
        "Sam Blackwell",
        "Sam Petulla",
        "Samantha R. Oates",
        "Santana Lujan",
        "Sean Shi",
        "Sebastian Castillo",
        "Sebastiano Aiello",
        "Seong Hyun Park",
        "Sergio Boixo",
        "Sergo Golovachev",
        "Sergei B. Bodrov",
        "Sergei B. Popov",
        "Sergei Gunin",
        "Sergei I. Blinnikov",
        "Sergei Nayakshin",
        "Sergei Popov",
        "Sergei Tyul'bashev",
        "Sergei Yu. Alekseev",
        "Sergey Samsonov",
        "Sergey Sazonov",
        "Sergey Tsygankov",
        "Sergey V. Troitsky",
        "Shakeel Ahmad",
        "Shashi B. Pandey",
        "Shashwat Kumar",
        "Shubham Srivastav",
        "Simon Blyth",
        "Soren Brandt",
        "Stanislav Komorovsky",
        "Stefania Maria Beolè",
        "Stefano De Padova",
        "Stein E. Haaland",
        "Stepan Dergachev",
        "Subhash Bose",
        "Sung-Chul Yoon",
        "Svetlana Biktemerova",
        "Sylvain Chaty",
        "Szymon Bugiel",
        "T. Adam",
        "T. Arai",
        "T. Arihara",
        "T. H. Bui",
        "T. J. Moriya",
        "T. Parsotan",
        "Taiqi Wang",
        "Tara Murphy",
        "Tatiana Antoshkina",
        "Tatiana Bogatenko",
        "Tatiana Zemskova",
        "Thies Kersten",
        "Thilo Birkenfeld",
        "Thomas Adam",
        "Thomas M. Tauris",
        "Timo Ahola",
        "Tim Burger",
        "Tim Lukas Holch",
        "Tiago Cardal Pais",
        "Tom Westerhout",
        "Torsha Moitra",
        "Trond I. Andersen",
        "Trond Andersen",
        "Tung Nguyen",
        "Tyler Cochran",
        "V. A. Chernyshev",
        "V. A. Kramarenko",
        "V. Baranov",
        "V. Burtsev",
        "V. D. Kulakovskii",
        "V. Mitin",
        "V. N. Frolov",
        "V. S. Knyazeva",
        "V. Shikin",
        "Vadim V. Ivanov",
        "Valentina N. Muratova",
        "Victor Doroshenko",
        "Viacheslav V. Zhuravlev",
        "Vinka Dakić",
        "Vinnu Bhardwaj",
        "Vittorio Vitale",
        "Vito Antonelli",
        "Vlad Shakhuro",
        "Vladimir Belavin",
        "Vladimir G. Malkin",
        "Vladimir Kukushkin",
        "Vladimir Lipunov",
        "Vladimir M. Lipunov",
        "Vladimir Mitin",
        "Vladimir Shikin",
        "Vladimir Solodkin",
        "Vladimir Sotnikov",
        "Vladislav D. Kurilovich",
        "Vladimir Yugay",
        "Wako Aoki",
        "Waleed Bin Qaim",
        "Weidong Bai",
        "Wenjing Deng",
        "Xiao Mi",
        "Xuan Yang",
        "Y. Awataguchi",
        "Y. Chikina",
        "Y. N. Ovchinnikov",
        "Y. R. Temiraev",
        "Y. A. Dvorkovich",
        "Y. D. Hu",
        "Y. M. Zhu",
        "Yana Safonova",
        "Yannick Stade",
        "Yaroslav Ispolatov",
        "Yaxing Zhang",
        "Yi-Ming Zhu",
        "Yongbo Huang",
        "Yongrui Wang",
        "Yu Yao",
        "Yu. A. Sergeev",
        "Yu. Chikina",
        "Yu. N. Ovchinnikov",
        "Yun Wang",
        "Yuri D. Lensky",
        "Zhixiong Dong",
        "Zhi-Ping Jin",
        "Zijun Chen",
        "Ziwen Han",
        "Zorawar Wadiasingh"
    ]

    if choice == "1":
        # Парсинг и сохранение статей
        search_query = input("Enter search query: ").strip()
        if not search_query:
            search_query = "machine learning"  # значение по умолчанию
        for search_query in lst:
            result = saver.save_parsed_data(search_query)
            print(f"\nResult: {result}")

    elif choice == "2":
        # Получение рекомендаций
        author_name = input("Enter author name: ").strip()
        if not author_name:
            print("Author name is required!")
            return

        # Инициализация рекомендательной системы
        db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'science_articles.db')
        engine = create_engine(f'sqlite:///{db_path}')

        recommender = ScienceRecommender(engine)
        recommender.train()

        recommendations = recommender.get_recommendations(author_name)

        print(f"\n--- Recommendations for: {author_name} ---")
        if isinstance(recommendations, list) and recommendations and isinstance(recommendations[0], dict):
            for i, rec in enumerate(recommendations, 1):
                print(f"{i}. {rec['name']} | Direction: {rec['direction']} | Score: {rec['score']}%")
                print(f"   Reason: {rec['reason']}\n")
        else:
            print(recommendations)

    elif choice == "3":
        # Демо-режим
        print("\n=== DEMO MODE ===")

        # Парсим несколько тем
        demo_targets = ["deep learning", "quantum computing", "bioinformatics"]
        results = saver.parse_multiple_targets(demo_targets)

        # Показываем рекомендации
        db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'science_articles.db')
        engine = create_engine(f'sqlite:///{db_path}')

        recommender = ScienceRecommender(engine)
        recommender.train()

        print("\n=== DEMO RECOMMENDATIONS ===")
        # Попробуем найти рекомендации для случайных авторов из базы
        demo_authors = ["Alex", "Smith", "Wang", "Johnson"]  # Замените на реальные имена из вашей базы

        for author in demo_authors:
            try:
                recs = recommender.get_recommendations(author)
                if isinstance(recs, list) and recs and isinstance(recs[0], dict):
                    print(f"\nRecommendations for {author}:")
                    for rec in recs[:2]:  # Показываем только 2 рекомендации
                        print(f"  - {rec['name']} ({rec['direction']}) - {rec['score']}%")
            except:
                print(f"\nNo recommendations for {author} (author not found)")

    else:
        print("Invalid choice!")


if __name__ == "__main__":
    main()